### ISSUE TITLE
Animated back to top button with CSS

### ISSUE THREAD

**Issue by LITUATUI** [willfaught/paige#6]
The idea is to show a back to top button only after scrolling with CSS.

[This](https://www.freecodecamp.org/news/css-only-back-to-top-button/
) article shows some methods that only use CSS, no JS.

I especially like [this](https://codepen.io/t_afif/pen/ExwbZKQ/86f79c96520a0c864324db70a6b76c76) method with a fading button.

What do you guys think?

**Comment by willfaught** [comment]
@LITUATUI Sorry for the delay responding. Somehow I was unsubscribed from issue notifications.

Are you proposing to add this to the default design, or reporting that it's not possible to do?

Since browsers already have a way to "scroll to top" (e.g. <kbd>Cmd+Up</kbd> on Mac), I'm disinclined to make this part of the default design.

However, user should be able to add it easily. I believe you can achieve this with `partials/paige/head-last.html` and/or `partials/paige/body-last.html`.

**Comment by willfaught** [comment]
Closing for now. If you have more to add, please reopen the issue.
